### ISSUE TITLE
Content missing on Update Page and Download Page

### ISSUE THREAD

**Issue by danscodelab** [Pinpoint-Simulations/PPS777#16]
# Issue 

Why is there no content on the Updates Page?

Provide Updates on your Page regarding the progress as you do on your discord, maybe with different categories (Installer/Website and so on) otherwise the Page makes no sense

Also i suggest removing the download section till you provide something to download

**Comment by Spherrrical** [comment]
We are currently updating the website to a React framework version. The updates page will be updated once our new website comes out. The download page will be for the installation of the Installer.

**Comment by danscodelab** [comment]
Closing issue, similiar to #17
