### ISSUE TITLE
No spacing?

### ISSUE THREAD

**Issue by danscodelab** [Pinpoint-Simulations/PPS777#17]
# Issue

Why is there no spacing between the content and the footer section? The footer section is always directly under the main content section which doesn't make any sense and looks wierd in a visitors perspective

# Solution

Separate them (should be an easy fix)

**Comment by Megabrains44** [comment]
Hey, so again, as Spherical said, we will be eventually revamping the website to a react version, so hopefully it will look much better than the current version. Also, next time, can you put the issue in the website repo. Thanks!

**Comment by danscodelab** [comment]
> Hey, so again, as Spherical said, we will be eventually revamping the website to a react version, so hopefully it will look much better than the current version. Also, next time, can you put the issue in the website repo. Thanks!

Whoops you're right! Sorry for that!

I will close the issue once the website is updated!
Is there any way to help coding the react version of the website? If yes, i would like to help! 

Cheers

**Comment by danscodelab** [comment]
page updated - issue fixed
